from django.urls import path
from .views import *

urlpatterns = [
    path('user_list/',                        UsersListCreateAPIView.as_view()),
    path('user_create/',                      UsersListCreateAPIView.as_view()),
    path('user_detail/<int:pk>/',             UserDetailAPIView.as_view()),
    path('user_update/<int:pk>/',             UserDetailAPIView.as_view()),
    path('user_delete/<int:pk>/',             UserDetailAPIView.as_view()),
    path('users/<int:pk>/channels/',          UserChannelsListAPIView.as_view()),
    path('channels_list/',                    ChanelListCreateAPIView.as_view()),
    path('channels_create/',                  ChanelListCreateAPIView.as_view()),
    path('channels_detail/<int:pk>/',         ChanelDetailAPIView.as_view()),
    path('channels_update/<int:pk>/',         ChanelDetailAPIView.as_view()),
    path('channels_delete/<int:pk>/',         ChanelDetailAPIView.as_view()),
    path('channels/<int:pk>/videos/',         ChanelVideosListView.as_view()),
    path('channels/<int:pk>/stats/',          ChanelStatsView.as_view()),
    path('videos/search/',                    VideoSearchAPIView.as_view()),
    path('videos/top/',                       VideoTopAPIView.as_view()),
    path('videos_list/',                      VideoListCreateAPIView.as_view()),
    path('videos_create/',                    VideoListCreateAPIView.as_view()),
    path('video_detail/<int:pk>/',            VideoDetailAPIView.as_view()),
    path('video_update/<int:pk>/',            VideoDetailAPIView.as_view()),
    path('video_delete/<int:pk>/',            VideoDetailAPIView.as_view()),
    path('videos/<int:pk>/related/',          VideoRelatedAPIView.as_view()),
    path('videos/<int:pk>/comments/',         VideoCommentsListAPIView.as_view()),
    path('videos/<int:pk>/comments_create/',  VideoCommentCreateAPIView.as_view()),
    path('comments/<int:pk>/',                CommentDetailAPIView.as_view()),
    path('comments_delete/<int:pk>/',         CommentDetailAPIView.as_view()),
    path('videos/<int:pk>/like/',             VideoLikeAPIView.as_view()),
    path('videos/<int:pk>/likes_info/',       VideoLikesListAPIView.as_view()),
    path('stats/videos/',                     StatsVideosAPIView.as_view()),
    path('stats/users/',                      StatsUsersAPIView.as_view()),
    path('stats/channels/',                   StatsChannelsAPIView.as_view()),
    path("register/", RegisterAPIView.as_view()),
    path("login/", LoginAPIView.as_view()),
    path("profile/", ProfileAPIView.as_view()),
]